//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF2_ParticleConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TF2_ParticleConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Complete. Remember to update the VTF file&apos;s \&quot;basetexture\&quot; path..
        /// </summary>
        internal static string CONVERTION_DONE {
            get {
                return ResourceManager.GetString("CONVERTION_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting image files. Make sure your numbered image files are in the &apos;frames&apos; folder..
        /// </summary>
        internal static string ERROR_CONVERTION {
            get {
                return ResourceManager.GetString("ERROR_CONVERTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the MKS file. Make sure your numbered image files are in the &apos;frames&apos; folder..
        /// </summary>
        internal static string ERROR_CREATE_MKS {
            get {
                return ResourceManager.GetString("ERROR_CREATE_MKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating SHT/TGA files. Make sure your combined frame images don&apos;t exceed 2048x2048.
        /// </summary>
        internal static string ERROR_CREATE_SHT {
            get {
                return ResourceManager.GetString("ERROR_CREATE_SHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the Team Fortress 2 directory. Make sure it&apos;s in the default Steam directory..
        /// </summary>
        internal static string ERROR_DIRECTORY_TF2 {
            get {
                return ResourceManager.GetString("ERROR_DIRECTORY_TF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid images found. Place your numbered PNG image files (0.png, 1.png etc.) into the &apos;frames&apos; folder..
        /// </summary>
        internal static string ERROR_PNG_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_PNG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the Team Fortress 2 directory. Please select your Team Fortress 2\\bin folder to continue..
        /// </summary>
        internal static string FOLDER_BROWSE_DESC {
            get {
                return ResourceManager.GetString("FOLDER_BROWSE_DESC", resourceCulture);
            }
        }
    }
}
